# Generated by Django 4.2.4 on 2023-08-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('conputer', 'Computer'), ('food', 'Food'), ('kids', 'Kids'), ('home', 'Home')], max_length=40),
        ),
    ]
